### ISSUE TITLE
Installation fails via Homebrew

### ISSUE THREAD

**Issue by MrDrewShep** [trek10inc/awsets#23]
I'm unable to install via Homebrew. Further, visiting the Homebrew website, I cannot find any reference to the Trek10 tap.

```sh
❯ brew tap trek10inc/tap

Error: Invalid formula: /opt/homebrew/Library/Taps/trek10inc/homebrew-tap/Formula/awsets.rb
formulae require at least a URL
Error: Cannot tap trek10inc/tap: invalid syntax in tap!
```

**Comment by lpearson-trek10** [comment]
@MrDrewShep Do you happen to be on an M1 mac?

**Comment by MrDrewShep** [comment]
M1 Mac

**Comment by lpearson-trek10** [comment]
@MrDrewShep So that is the issue awsets doesn't currently have support ARM version for mac.  I don't have an M1 mac to test with, it could be setup to build for M1 but without having a way to test I would be a little hesitant to do that.  I am wondering if you could download the source and try following the build steps in the readme and let me know how it goes.

**Comment by MrDrewShep** [comment]
I did get it installed, and it worked successfully. I'm 99% sure that I built from source as opposed to downloading the binary.

**Comment by jcarter3** [comment]
I updated the tests/builds to support go 1.18 & arm64 builds - this should be resolved now via homebrew as well!
